
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 20:19:56 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int DIVIDE = 30;
  public static final int CONST = 5;
  public static final int LPAREN = 12;
  public static final int SEMI = 8;
  public static final int CONTINUE = 20;
  public static final int NUM_CONST = 45;
  public static final int MINUS = 28;
  public static final int RPAREN = 13;
  public static final int AND = 40;
  public static final int LCURL = 3;
  public static final int LS = 36;
  public static final int RECORD = 11;
  public static final int OR = 41;
  public static final int COMMA = 7;
  public static final int INC = 25;
  public static final int PLUS = 27;
  public static final int IF = 15;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int EQUAL = 6;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int PERCENT = 31;
  public static final int IDENT = 44;
  public static final int BREAK = 19;
  public static final int VOID = 14;
  public static final int EQ = 32;
  public static final int LBRACK = 9;
  public static final int RCURL = 4;
  public static final int TIMES = 29;
  public static final int COLON = 42;
  public static final int ELSE = 16;
  public static final int READ = 22;
  public static final int RBRACK = 10;
  public static final int NOT_EQ = 33;
  public static final int GOTO = 24;
  public static final int QUEST = 43;
  public static final int WHILE = 18;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 46;
  public static final int GR_EQ = 35;
  public static final int LS_EQ = 37;
  public static final int DEC = 26;
  public static final int GR = 34;
  public static final int PRINT = 23;
  public static final int DO = 17;
}

